HELP_TEXT = (
    "Это анонимный чат ТГАЧ\n\n"
    "Команды:\n"
    "/start - начать\n"
    "/help - помощь\n"
    "/stats - статистика\n"
    "/face \n"
    "/roll – ролл 0-100 или /roll N\n"
    "/invite - получить текст для приглашения анонов\n"
    "/deanon - деанон постера\n"
    "/zaputin - активировать режим zaputin\n"
    "/slavaukraine - активировать режим slavaukraine\n"
    "/suka_blyat - активировать режим suka_blyat\n"
    "/anime - активировать аниме-режим\n\n"
    "Все сообщения анонимны!"
)
