HELP_TEXT = (
    "Это анонимный чат ТГАЧ. Просто пиши сообщения, они будут отправлены всем анонимно. Всем от всех.\n\n"
    "Команды:\n"
    "/start - начать\n"
    "/help - помощь\n"
    "/stats - статистика\n"
    "/face \n"
    "/roll – ролл 0-100 или /roll N\n"
    "/invite - получить текст для приглашения анонов\n"
    "/deanon - деанон постера\n"
    "/active - активность досок\n"
    "/zaputin - активировать режим zaputin\n"
    "/slavaukraine - активировать режим slavaukraine\n"
    "/suka_blyat - активировать режим suka_blyat\n"
    "/anime - активировать аниме-режим\n\n"
    "Все сообщения анонимны!"
)

HELP_TEXT_EN = (
    "This is TGACH, an anonymous chat. Just send messages, and they will be sent to everyone anonymously. From everyone, to everyone.\n\n"
    "Commands:\n"
    "/start - start the bot\n"
    "/help - show this help message\n"
    "/stats - show statistics\n"
    "/face - get a random face\n"
    "/roll – roll a number from 0-100\n"
    "/invite - get a text to invite new anons\n"
    "/deanon - de-anonymize a poster\n"
    "/active - активность досок\n"
    "/anime - activate anime-mode\n\n"
    "All messages are anonymous!"
)
