[phases.setup]
cmds = [
    "apt-get update",
    "apt-get install -y git"
]

[phases.install]
cmds = [
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "echo 'Building...'"
]

[phases.start]
cmd = "python -u тест.py"
